#!/bin/sh

if [ $# -ne 3 ]; then
    echo $0 "set id type"
    exit
fi

IN=$(dirname $0)/../template/template.$3
OUT=$(dirname $0)/../problems/$1/$1$2.$3

cd $(dirname $0)/../problems

prepare-directory $1

if [ -e $OUT ]; then
    echo $OUT " already exists."
else
    cat $IN | sed -e "s/<id>/$1$2/g" > $OUT
fi
